// --------------------------------------------------------------------------------------------------------------------
// <copyright file="SupplierRepository.cs" company="EPAM Systems India">
//   Copyright 2015
// </copyright>
// <summary>
//   Autogenerated Web Services
// </summary>
// --------------------------------------------------------------------------------------------------------------------
namespace InternalApp.Repository
{
    using Entities;
    using global::Repository.Pattern.DataContext;
    using global::Repository.Pattern.Ef6;
    using global::Repository.Pattern.UnitOfWork;
    
	/// <summary>
    /// The supplier service.
    /// </summary>
    public class SupplierRepository : Repository<Supplier>, ISupplierRepository
    {
		/// <summary>
        /// Initializes a new instance of the <see cref="SupplierRepository"/> class.
        /// </summary>
        /// <param name="context">
        /// The context.
        /// </param>
        /// <param name="unitOfWork">
        /// The unit of work.
        /// </param>
        public SupplierRepository(IDataContextAsync context, IUnitOfWorkAsync unitOfWork)
            : base(context, unitOfWork)
        { }
	}
}
