// --------------------------------------------------------------------------------------------------------------------
// <copyright file="ICategoryRepository.cs" company="EPAM Systems India">
//   Copyright 2015
// </copyright>
// <summary>
//   Autogenerated Web Services
// </summary>
// --------------------------------------------------------------------------------------------------------------------
namespace InternalApp.Repository
{
	using Entities;
	using global::Repository.Pattern.Repositories;

    /// <summary>
    /// The category Repository interface
    /// </summary> 
    public interface ICategoryRepository : IRepositoryAsync<Category>
    { }   
}
