// --------------------------------------------------------------------------------------------------------------------
// <copyright file="ICategoryService.cs" company="EPAM Systems India">
//   Copyright 2015
// </copyright>
// <summary>
//   Autogenerated Web Services
// </summary>
// --------------------------------------------------------------------------------------------------------------------
namespace InternalApp.Services
{
	using Entities;
	using Service.Pattern;

    /// <summary>
    /// The category service interface
    /// </summary>
    public interface ICategoryService : IService<Category>
    { }
}
