// --------------------------------------------------------------------------------------------------------------------
// <copyright file="ISupplierService.cs" company="EPAM Systems India">
//   Copyright 2015
// </copyright>
// <summary>
//   Autogenerated Web Services
// </summary>
// --------------------------------------------------------------------------------------------------------------------
namespace InternalApp.Services
{
	using Entities;
	using Service.Pattern;

    /// <summary>
    /// The supplier service interface
    /// </summary>
    public interface ISupplierService : IService<Supplier>
    { }
}
